matrix:
  include:
  - os: linux
    env: TARGET=linux

language: node_js

node_js:
  - "6.10"

script:
  - node --version
  - npm --version
  - npm install
  - npm run electron:$TARGET
  - zip -r build.zip app-builds/T-Rec-*/

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change