os:
  - linux

language: node_js

node_js:
  - "6.10"

script:
  - node --version
  - npm --version
  - npm install
  - npm run electron:linux

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change
